[2025-03-31T13:19:09.443-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T13:19:09.449-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exec_mult_tasks.taskC manual__2025-03-31T18:18:56.165989+00:00 [queued]>
[2025-03-31T13:19:09.452-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exec_mult_tasks.taskC manual__2025-03-31T18:18:56.165989+00:00 [queued]>
[2025-03-31T13:19:09.453-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T13:19:09.640-0500] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): taskC> on 2025-03-31 18:18:56.165989+00:00
[2025-03-31T13:19:09.641-0500] {standard_task_runner.py:72} INFO - Started process 425322 to run task
[2025-03-31T13:19:09.643-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'exec_mult_tasks', 'taskC', 'manual__2025-03-31T18:18:56.165989+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/exec_multiple_tasks.py', '--cfg-path', '/tmp/tmpp_djlowm']
[2025-03-31T13:19:09.644-0500] {standard_task_runner.py:105} INFO - Job 44: Subtask taskC
[2025-03-31T13:19:09.861-0500] {task_command.py:467} INFO - Running <TaskInstance: exec_mult_tasks.taskC manual__2025-03-31T18:18:56.165989+00:00 [running]> on host royal-07.cs.wisc.edu
[2025-03-31T13:19:10.711-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cloud.user' AIRFLOW_CTX_DAG_ID='exec_mult_tasks' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T18:18:56.165989+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T18:18:56.165989+00:00'
[2025-03-31T13:19:10.711-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T13:19:10.719-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-31T13:19:10.720-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', 'tmpazpl3iis.sh']
[2025-03-31T13:19:10.723-0500] {subprocess.py:99} INFO - Output:
[2025-03-31T13:19:10.723-0500] {subprocess.py:106} INFO - TASK C has started!
[2025-03-31T13:19:20.724-0500] {subprocess.py:110} INFO - Command exited with return code 130
[2025-03-31T13:19:20.728-0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2025-03-31T13:19:20.753-0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=exec_mult_tasks, task_id=taskC, run_id=manual__2025-03-31T18:18:56.165989+00:00, execution_date=20250331T181856, start_date=20250331T181909, end_date=20250331T181920
[2025-03-31T13:19:21.051-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T13:19:21.051-0500] {standard_task_runner.py:124} ERROR - Failed to execute job 44 for task taskC (Bash command failed. The command returned a non-zero exit code 130.; 425322)
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2025-03-31T13:19:21.081-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-31T13:19:21.087-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T13:19:21.205-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
