[2025-03-31T13:01:16.400-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T13:01:16.406-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exec_mult_tasks.4 manual__2025-03-31T18:01:01.116987+00:00 [queued]>
[2025-03-31T13:01:16.409-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exec_mult_tasks.4 manual__2025-03-31T18:01:01.116987+00:00 [queued]>
[2025-03-31T13:01:16.410-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T13:01:16.569-0500] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): 4> on 2025-03-31 18:01:01.116987+00:00
[2025-03-31T13:01:16.571-0500] {standard_task_runner.py:72} INFO - Started process 414258 to run task
[2025-03-31T13:01:16.572-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'exec_mult_tasks', '4', 'manual__2025-03-31T18:01:01.116987+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/exec_multiple_tasks.py', '--cfg-path', '/tmp/tmps698v9je']
[2025-03-31T13:01:16.573-0500] {standard_task_runner.py:105} INFO - Job 36: Subtask 4
[2025-03-31T13:01:16.728-0500] {task_command.py:467} INFO - Running <TaskInstance: exec_mult_tasks.4 manual__2025-03-31T18:01:01.116987+00:00 [running]> on host royal-07.cs.wisc.edu
[2025-03-31T13:01:17.003-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cloud.user' AIRFLOW_CTX_DAG_ID='exec_mult_tasks' AIRFLOW_CTX_TASK_ID='4' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T18:01:01.116987+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T18:01:01.116987+00:00'
[2025-03-31T13:01:17.004-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T13:01:17.012-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-31T13:01:17.012-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Task 4 executed']
[2025-03-31T13:01:17.015-0500] {subprocess.py:99} INFO - Output:
[2025-03-31T13:01:17.015-0500] {subprocess.py:106} INFO - Task 4 executed
[2025-03-31T13:01:17.016-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-31T13:01:17.123-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T13:01:17.123-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=exec_mult_tasks, task_id=4, run_id=manual__2025-03-31T18:01:01.116987+00:00, execution_date=20250331T180101, start_date=20250331T180116, end_date=20250331T180117
[2025-03-31T13:01:17.386-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T13:01:17.391-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T13:01:17.392-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
